spring:
  application:
    name: hackaton
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/hackaton
          jwk-set-uri: ${keycloak.base-url}/realms/hackaton/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: fiaphackaton8@gmail.com
    password: rram txjv hxjk xpmi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: a7ab2f544d40a41b9992c96cd08cb6a1-1119168641.us-east-1.elb.amazonaws.com
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://hackaton-database.clqlggnukv17.us-east-1.rds.amazonaws.com:5432/hackaton
    username: postgres
    password: postgres
  jpa:
    database: Postgresql
    show-sql: true
    open-in-view: false
  #    hibernate:
  #      ddl-auto: create
  flyway:
    schemas: hackaton
    url: jdbc:postgresql://hackaton-database.clqlggnukv17.us-east-1.rds.amazonaws.com:5432/hackaton
    user: postgres
    password: postgres
minio:
  endpoint: http://ad37b0f95c51847739e56622b405ab8b-1629192107.us-east-1.elb.amazonaws.com:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: images-bucket
  # http://acc74b97162fd4fc6b9066b72b8272d8-1402821327.us-east-1.elb.amazonaws.com/realms/hackaton/protocol/openid-connect/token
keycloak:
  base-url: http://acc74b97162fd4fc6b9066b72b8272d8-1402821327.us-east-1.elb.amazonaws.com
  auth-server-url: ${keycloak.base-url}
  token-url: ${keycloak.base-url}/realms/hackaton/protocol/openid-connect/token
  users-url: ${keycloak.base-url}/admin/realms/hackaton/users
  realm: hackaton
  client-id: hackaton-app
  client-key-password: mQEilYGAST1DJTM6Stsfb7cFuQHTXomW
  admin-username: root
  admin-password: root
  use-resource-role-mappings: true
  bearer-only: false
  security-constraints:
    - security-collections:
        - name: secured
          patterns:
            - /api/*
output:
  folder: imagens-processadas/
