spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/hackaton
          jwk-set-uri: http://localhost:8082/realms/hackaton/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: fiaphackaton8@gmail.com
    password: rram txjv hxjk xpmi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: hackaton
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/hackaton
    username: myappuser
    password: myapppassword

  jpa:
    database: Postgresql
    show-sql: true
    open-in-view: false
  #    hibernate:
  #      ddl-auto: create
  flyway:
    schemas: hackaton
    url: jdbc:postgresql://localhost:5432/hackaton
    user: postgres
    password: postgres

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: images-bucket

output:
  folder: imagens-processadas/