spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://a1ba8e5fcf0cd4c6f971b7e421a6a2da-1113462717.us-east-1.elb.amazonaws.com/realms/hackaton
          jwk-set-uri: http://a1ba8e5fcf0cd4c6f971b7e421a6a2da-1113462717.us-east-1.elb.amazonaws.com/realms/hackaton/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: 587
    username: fiaphackaton8@gmail.com
    password: rram txjv hxjk xpmi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: hackaton
  rabbitmq:
    host: aa729f2d2f8494ef187f203474f6bd08-1191370861.us-east-1.elb.amazonaws.com
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://postgres-db-fast-food.clqlggnukv17.us-east-1.rds.amazonaws.com:5432/hackaton
    username: postgres
    password: postgres

  jpa:
    database: Postgresql
    show-sql: true
    open-in-view: false
  #    hibernate:
  #      ddl-auto: create
  flyway:
    schemas: hackaton
    url: jdbc:postgresql://postgres-db-fast-food.clqlggnukv17.us-east-1.rds.amazonaws.com:5432/hackaton
    user: postgres
    password: postgres

minio:
  endpoint: http://ab13a7b3ce47d4e33a055ae3396d01d0-1385393272.us-east-1.elb.amazonaws.com:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: images-bucket

keycloak:
  base-url: http://a1ba8e5fcf0cd4c6f971b7e421a6a2da-1113462717.us-east-1.elb.amazonaws.com
  auth-server-url: ${keycloak.base-url}
  token-url: ${keycloak.base-url}/realms/hackaton/protocol/openid-connect/token
  users-url: ${keycloak.base-url}/admin/realms/hackaton/users
  realm: hackaton
  client-id: hackaton-app
  client-key-password: 9NvgvxFH2Rk4xqfgIYBRphogHQqRNCP5
  admin-username: root
  admin-password: root
  use-resource-role-mappings: true
  bearer-only: false
  security-constraints:
    - security-collections:
        - name: secured
          patterns:
            - /api/*

output:
  folder: imagens-processadas/