server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hackaton
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  host: localhost
  port: 5672

keycloak:
  base-url: http://localhost:8082
  auth-server-url: ${keycloak.base-url}
  token-url: ${keycloak.base-url}/realms/hackaton/protocol/openid-connect/token
  users-url: ${keycloak.base-url}/admin/realms/hackaton/users
  realm: hackaton
  client-id: admin-cli
  admin-username: root
  admin-password: root
  use-resource-role-mappings: true
  bearer-only: false
  security-constraints:
    - security-collections:
        - name: secured
          patterns:
            - /api/*

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework: DEBUG