server:
  port: 8081 # Spring Boot application port

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hackaton # Connect to PostgreSQL on localhost
    username: postgres                          # PostgreSQL username
    password: postgres                      # PostgreSQL password
    driver-class-name: org.postgresql.Driver     # PostgreSQL driver
  jpa:
    hibernate:
      ddl-auto: update                           # Update schema automatically for local dev
    show-sql: true                               # Show SQL queries in logs
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  host: localhost                                # Connect to RabbitMQ on localhost
  port: 5672                                     # RabbitMQ port

keycloak:
  auth-server-url: http://localhost:8082/auth    # Keycloak base URL on localhost
  realm: myrealm                                 # Keycloak realm
  resource: myapp                                # Client ID for your application
  credentials:
    secret: mysecret                             # Client secret for the client
  use-resource-role-mappings: true              # Enable resource role mappings
  bearer-only: false                            # Set to true if the app doesn't initiate login
  security-constraints:
    - security-collections:
        - name: secured
          patterns:
            - /api/*                             # Protected paths

logging:
  level:
    root: INFO                                   # Default log level
    org.hibernate.SQL: DEBUG                     # Show Hibernate SQL statements
    org.springframework: DEBUG                   # Show detailed Spring logs