server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-db-fast-food.clqlggnukv17.us-east-1.rds.amazonaws.com:5432/hackaton
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  host: localhost
  port: 5672

keycloak:
  base-url: http://a1ba8e5fcf0cd4c6f971b7e421a6a2da-1113462717.us-east-1.elb.amazonaws.com
  auth-server-url: ${keycloak.base-url}
  token-url: ${keycloak.base-url}/realms/hackaton/protocol/openid-connect/token
  users-url: ${keycloak.base-url}/admin/realms/hackaton/users
  realm: hackaton
  client-id: hackaton-app
  client-key-password: 9NvgvxFH2Rk4xqfgIYBRphogHQqRNCP5
  admin-username: root
  admin-password: root
  use-resource-role-mappings: true
  bearer-only: false
  security-constraints:
    - security-collections:
        - name: secured
          patterns:
            - /api/*


logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.springframework: INFO