apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-hackaton-api
  labels:
    app: pod-hackaton-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-hackaton-api
  template:
    metadata:
      labels:
        app: pod-hackaton-api
    spec:
      containers:
        - name: backend-hackaton-api
          image: 566814225519.dkr.ecr.us-east-1.amazonaws.com/pos-fiap-schepis/hackaton-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"