apiVersion: v1
kind: Service
metadata:
  name: svc-hackaton-api
spec:
  selector:
    app: pod-hackaton-api
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 8080 # Internal container port
  type: LoadBalancer