CREATE TABLE VIDEO_PROCESSOR_METADATA (
id BIGINT PRIMARY KEY NOT NULL,
mb NUMERIC NOT NULL,
filename VARCHAR(200) NOT NULL,
seconds INTEGER NOT NULL
);

CREATE SEQUENCE SQ_VIDEO_PROCESSOR_METADATA
    INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;