CREATE TABLE VIDEO_PROCESSOR_REQUEST (
id VARCHAR(100) PRIMARY KEY NOT NULL,
id_metadata BIGINT NOT NULL,
date_request TIMESTAMP NOT NULL,
user_app VARCHAR(100) NOT NULL,
email VARCHAR(200) NOT NULL,
status VARCHAR(30) NOT NULL
);

ALTER TABLE VIDEO_PROCESSOR_REQUEST
    ADD CONSTRAINT fk_video_processor_metadata
        FOREIGN KEY (id_metadata)
            REFERENCES VIDEO_PROCESSOR_METADATA(id);