CREATE TABLE VIDEO_PROCESSOR_REQUEST (
id BIGINT PRIMARY KEY NOT NULL,
id_request VARCHAR(100) NOT NULL,
id_metadata BIGINT NOT NULL,
date_request TIMESTAMP NOT NULL,
user_app VARCHAR(100) NOT NULL,
email VARCHAR(200) NOT NULL,
status VARCHAR(30) NOT NULL
);

CREATE SEQUENCE SQ_VIDEO_PROCESSOR_REQUEST
    INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

ALTER TABLE VIDEO_PROCESSOR_REQUEST
    ADD CONSTRAINT fk_video_processor_metadata
        FOREIGN KEY (id_metadata)
            REFERENCES VIDEO_PROCESSOR_METADATA(id);